name: deferred_indexed_stack
description: "IndexedStack with possibility to defer initialization of content"
version: 0.0.4
repository: https://github.com/Lifeyear/deferred_indexed_stack

topics: 
  - performance
  - widgets
  - flutter

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
